[package]
name = "osm-registry-guest"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
osm-registry-core = { path = "../../registry_core" }
borsh = { workspace = true }
serde = { workspace = true }
risc0-zkvm = { version = "3.0", default-features = false, features = ["std"] }
lee_core = { path = "/tmp/lez/lee/state_machine/core" }

[[bin]]
name = "osm_registry"
path = "src/bin/osm_registry.rs"
test = false
