[package]
name = "osm-registry-guest"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
osm-registry-core = { path = "../../registry_core" }
borsh = { workspace = true }
serde = { workspace = true }

[[bin]]
name = "osm_registry"
path = "src/bin/osm_registry.rs"
test = false
