[package]
name = "osm-registry-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
osm-registry-core = { path = "../registry_core" }
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[[test]]
name = "registry_tests"
path = "registry_tests.rs"
